### ISSUE TITLE
Provide alternative Access to `HTTP_AUTHORIZATION` Header

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#106]
`PHP_AUTH_USER/PWD` is missing here (https://github.com/atrocore/atrocore/blob/d0ad0734cb6987d73c6c844d80a4db7f3c53cbf0/app/Espo/Core/Utils/Api/Auth.php#L83) when PHP runs as CGI/FastCGI, even when adding Headers back in the .htaccess file like this: `SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`

A fallback could be something like this:

```php
        if (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
           list($authUsername, $authPassword) = explode(':' , base64_decode(substr($_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 6)));
        }else{
            $authUsername = $req->headers('PHP_AUTH_USER');
            $authPassword = $req->headers('PHP_AUTH_PW');
        }
```

As described here: https://github.com/atrocore/atropim/discussions/113#discussioncomment-630207

**Comment by rratsun** [comment]
Ok. We added this issue to our backlog and will do it soon.

**Comment by rratsun** [comment]
Added in atrocore 1.2.28 or above.
