### ISSUE TITLE
config setting to set the php binary path manually

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#109]
The cronjob script determents the location of php cli version automatically

https://github.com/atrocore/atrocore/blob/master/app/Espo/Core/Utils/System.php#L117

Please provide a config key to set the php binary path manually.

In my case the binary is detected at `/usr/bin/php` which is a symlink to the wrong php version therefore key functionality fails.

See: https://github.com/atrocore/atropim/discussions/114#discussioncomment-640152

**Comment by rratsun** [comment]
We added this issue to our backlog and will do it soon.

**Comment by rratsun** [comment]
Hello

We added ability to set php binary path manually. For this you should set ```phpBinPath``` parameter in ```data/config.php```. But firstly you should update  atrocore to 1.2.27 or above.

Example:
```
...
'phpBinPath' => 'php',
...
```

**Comment by marcus-at-localhost** [comment]
Works like charm! Thank you so much
