### ISSUE TITLE
After upgrade to 1.8.41 classification_hierarchy doesn't exist

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#1119]
Hello,
After updating from 1.8.40 to 1.8.41 i get this error everywhere classification is showing. Classification itself or trying to change classifixcation on a product.

SQLSTATE[42S02]: Base table or view not found: 1146 Table '<>DATABASENAME<>.classification_hierarchy' doesn't exist

You have the same error on demo.atropim.com

**Comment by AnnZast** [comment]
Hello, 
We have created a ticket in the internal system to fix this bug. I will let you know when it is fixed

**Comment by exeqtwasnotfree** [comment]
This now works in v1.9.1
