### ISSUE TITLE
400 Bad Request when saving export-job

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#1156]
Hello.
I have found that if I edit an export-job, a filed named "Template Name" appears.
Before edit:
![bild](https://github.com/atrocore/atrocore/assets/99046110/e5422159-f1ce-4256-9872-1c9084c150a4)
(no "Template Name" - field)
During edit:
![bild](https://github.com/atrocore/atrocore/assets/99046110/2764e73d-da2a-4088-a6de-f0f2538a4d72)
After abort or save i get:
400 Bad Request
<PIM-SERVER-URL>/api/v1/ExportFeed/action/getOriginTemplate?template=
I can´t find anywhere I can add or edit a template, or if a need any? but the page don't like it.

**Comment by AnnZast** [comment]
Hello 
Recently, we added the ability to choose a template for export of type HTTP Request, as a result, this field was added to the file type as well. You are right, it is not needed here. We will fix this in the next release.

**Comment by AnnZast** [comment]
Hello
We have already fixed this issue. You can update to check it.
