### ISSUE TITLE
Unable to install atrocore in my windows Laptop for my organisation. 

### ISSUE THREAD

**Issue by Tushar030790** [atrocore/atrocore#1262]
Hi Team, I am trying to import the csv file of product details but it is showing always pending. Please help me with the proper step by step process to install the atroPIM in my windows for my organisation.

**Comment by atrolex** [comment]
Hi, I assume the Cron jobs are not working. Check our requirements and your installation. The system will not work on a managed server or some hosting.

**Comment by Tushar030790** [comment]
Issue resolved. Thank you.
