### ISSUE TITLE
Bad  server response 

### ISSUE THREAD

**Issue by ahmedali991** [atrocore/atrocore#1273]
Hello guys 
i recently deployed atrocore all goes well but after  deploying i got bad server response in the home page 
![atrocore-error](https://github.com/atrocore/atrocore/assets/119056947/7ae65d49-6707-47d8-a389-f330dd06aaf1)
[atro-2024-05-10.log](https://github.com/atrocore/atrocore/files/15271885/atro-2024-05-10.log)
i attached log file form my server 
if could someone to help me solve this issue 
thanks

**Comment by rratsun** [comment]
Hello, 
Unfortunatelly, it is a bug in ProductTypes dashlet. Thank you to help us to find it. We will fix it in the next relase of pim module.

**Comment by rratsun** [comment]
Hello, the bug has been solved at PIM 1.13.10. Please, update your instalation.
