### ISSUE TITLE
After an update we get this error: Uncaught Exception TypeError "get_object_vars() expects parameter 1 to be object, array given"

### ISSUE THREAD

**Issue by giuseppe-ao** [atrocore/atrocore#1275]
Unfortunately, we do not know the version of Atro installed. Because we do not have access to the server.  Our provider just told us that there is this error in the logs.

`[2024-05-13T15:23:07.948295+00:00] Log.ERROR: Uncaught Exception TypeError: "get_object_vars() expects parameter 1 to be object, array given" at /var/www/[media.adriasonline.it/vendor/atrocore/core/app/Espo/Core/Utils/Metadata.php](http://media.adriasonline.it/vendor/atrocore/core/app/Espo/Core/Utils/Metadata.php) line 431 {"exception":"[object] (TypeError(code: 0): get_object_vars() expects parameter 1 to be object, array given at /var/www/[media.adriasonline.it/vendor/atrocore/core/app/Espo/Core/Utils/Metadata.php:431](http://media.adriasonline.it/vendor/atrocore/core/app/Espo/Core/Utils/Metadata.php:431))"} []`

**Comment by rratsun** [comment]
Hello, it is a strange error. We haven't seen it before. We will fix it in the next release.

**Comment by rratsun** [comment]
The problem has been fixed in Core 1.10.14. Please, update your system.

**Comment by giuseppe-ao** [comment]
After the update, the dashboard started working again, but we can no longer find the images. 

We have only launched a scan procedure of the stogare to try to restore the files that are not found by the application (but are somehow present given the occupied disk space) by logging into media.adriasonline.it with your user, going to Settings -> Administration -> Storage -> Base -> Scan 

The job failed. Attached is the screenshot.

![Schermata 2024-05-31 alle 10 56 17](https://github.com/atrocore/atrocore/assets/74664595/7d668b10-d329-4985-879d-7b41ab971137)

**Comment by AnnZast** [comment]
Hello,
This error looks very weird. Could you please tell us if there were any errors in the logs after the update? And were there any interventions in the code from your side? 
We recommend you to purchase Bronze Support https://store.atrocore.com/en/support-package-bronze/20118 and give us access to your server so that we can fix the situation ourselves

**Comment by giuseppe-ao** [comment]
Good morning @AnnZast, we purchased the bronze package for assistance. What is the channel to request the help. What do you need to proceed to solve this problem? 
Thank you very much

**Comment by AnnZast** [comment]
Hello
Please write your email address here or email me on anna.zastavenko@atrocore.com so that we can further interact
