### ISSUE TITLE
BUG import & track change

### ISSUE THREAD

**Issue by Vladzimir** [atrocore/atrocore#1284]
![Screenshot(119)](https://github.com/atrocore/atrocore/assets/5346225/b2b801f2-5088-4182-bcba-17206bb7c855)
After import SKU, stream empty
![Screenshot(120)](https://github.com/atrocore/atrocore/assets/5346225/7771ea93-349a-4f5f-b0ca-09aba91df1e5)

**Comment by AnnZast** [comment]
You are right, there is a bug and the information about changing fields is not displayed in the stream if they were changed by import. I will create a task in our internal system to fix it

**Comment by AnnZast** [comment]
Hello Vladzimir,
After a detailed analysis of the problem, we realized that field tracking during import was disabled on purpose to avoid performance degradation when importing a large amount of data. This is a temporary measure until we refactor the notation of changes in the system as a whole. This problem will be solved in the near future

**Comment by Vladzimir** [comment]
FIX in 1.10.39 https://help.atrocore.com/release-notes/core#1-10-39 

> Refactored the notation of changes in the system so that the tracking of fields and attributes during import does not affect the import performance.

**Comment by Vladzimir** [comment]
FIX in 1.10.39 https://help.atrocore.com/release-notes/core#1-10-39 

> Refactored the notation of changes in the system so that the tracking of fields and attributes during import does not affect the import performance.
