### ISSUE TITLE
Missing Column after Update

### ISSUE THREAD

**Issue by paultvis** [atrocore/atrocore#1285]
I have just upgraded to the latest version to help with the API file import. However, following the upgrade when I load the login page I am getting

 [2024-05-22T14:06:23.671615+00:00] Log.ERROR: Uncaught Exception PDOException: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.salutation_name' in 'field list'" at /var/www/atropim/vendor/atrocore/core/app/Espo/ORM/DB/Mapper.php line 77 {"exception":"[object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.salutation_name' in 'field list' at /var/www/atropim/vendor/atrocore/core/app/Espo/ORM/DB/Mapper.php:77)"} []

**Comment by rratsun** [comment]
In the new version of core such column does not exist. Are you sure update was without mistakes? 

Maybe you have this field in ```custom``` folder. If it is so try to execute ```php index.php sql diff --show``` to see what queries needs to be executed for preparing DB schema. And ```php index.php sql diff --run``` for execute that queries.

Hope it helps.

**Comment by paultvis** [comment]
I did not see any errors in the UI. Is there a log for the upgrade that I can check?

**Comment by paultvis** [comment]
And are there commands I can run in the terminal to rerun/complete the upgrade or it is case of just going through the composer modules?

**Comment by rratsun** [comment]
System will restore itself in case of error while upgrading. 

Can you show ugrade log? You can find it in Module Manager.

For update system:
php composer.phar update  (as www-data user)

For restore to previous version:
php composer.phar restore (as www-data user)

but module manager doing the same. firstly it tries to php composer.phar update, in case of errors while updating php composer.phar restore

**Comment by paultvis** [comment]
We cannot access the system so cannot see the Module Manager

**Comment by rratsun** [comment]
what about ```php index.php sql diff --show``` ?

**Comment by rratsun** [comment]
I recommend you to restore the system.
```php composer.phar restore```

Later try to update once more time.

**Comment by paultvis** [comment]
So took a while to get back to a good state for some reason but I have just run the update again and it has failed with the following
DETAILS
23.05.2024 09:38:16 | Loading composer repositories with package information
23.05.2024 09:38:18 | Creating restore point
23.05.2024 09:38:51 | Updating dependencies
23.05.2024 09:39:22 | Package operations: 3 installs, 21 updates, 1 removal
  - Removing symfony/workflow (v5.4.28)
  - Updating atrocore/compatibilities (1.0.2 => 1.0.6): 
  - Updating symfony/polyfill-php80 (v1.28.0 => v1.29.0): 
  - Updating symfony/deprecation-contracts (v2.5.2 => v2.5.3): 
  - Updating symfony/polyfill-mbstring (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-intl-normalizer (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-ctype (v1.28.0 => v1.29.0): 
  - Updating symfony/event-dispatcher-contracts (v2.5.2 => v2.5.3): 
  - Updating symfony/event-dispatcher (v5.4.26 => v5.4.39): 
  - Updating paragonie/constant_time_encoding (v2.6.3 => v2.7.0): 
  - Updating phpseclib/phpseclib (3.0.23 => 3.0.37): 
  - Updating symfony/polyfill-php72 (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-intl-idn (v1.28.0 => v1.29.0): 
  - Updating ezyang/htmlpurifier (v4.16.0 => v4.17.0): 
  - Updating caxy/php-htmldiff (v0.1.14 => v0.1.15): 
  - Installing ralouphie/getallheaders (3.0.3): 
  - Updating psr/http-factory (1.0.2 => 1.1.0): 
  - Installing guzzlehttp/psr7 (2.6.2): 
  - Updating atrocore/core (1.6.46 => 1.10.21): 
  - Updating atrocore/dam (1.5.22 => 1.8.3): 
  - Updating atrocore/pim (1.9.51 => 1.13.12): 
  - Updating twig/twig (v3.7.1 => v3.10.3): 
  - Installing jdorn/sql-formatter (v1.2.16): 
  - Updating atrocore/export-feeds (1.7.26 => 1.8.9): 
  - Updating atrocore/import-feeds (1.5.27 => 1.6.8): 
23.05.2024 09:39:41 | Writing lock file
23.05.2024 09:39:41 | Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> \Atro\Composer\PostUpdate::postUpdate
23.05.2024 09:39:41 | Updating list of used modules
23.05.2024 09:39:41 | Copying post-install & post-delete scripts for modules
23.05.2024 09:39:43 | Copying migration scripts
23.05.2024 09:39:43 | Clearing cache
23.05.2024 09:39:44 | Copying frontend files
23.05.2024 09:39:45 | Run migration Atro 1.6.51
23.05.2024 09:39:55 | Run migration Atro 1.6.54
23.05.2024 09:39:55 | Run migration Atro 1.7.34
23.05.2024 09:39:55 | Run migration Atro 1.7.35
23.05.2024 09:40:17 | Run migration Atro 1.7.36
23.05.2024 09:40:17 | Run migration Atro 1.7.37
23.05.2024 09:40:17 | Run migration Atro 1.8.2
23.05.2024 09:40:17 | Run migration Atro 1.8.3
23.05.2024 09:40:17 | Run migration Atro 1.8.6
23.05.2024 09:43:42 | Run migration Atro 1.8.7
23.05.2024 09:43:43 | Run migration Atro 1.8.8
23.05.2024 09:43:45 | Run migration Atro 1.8.10
23.05.2024 09:43:46 | Failed! There is no table with name 'atrocore.address' in the schema. {"file":"\/var\/www\/atropim\/vendor\/doctrine\/dbal\/src\/Schema\/Schema.php","line":189,"function":"tableDoesNotExist","class":"Doctrine\\DBAL\\Schema\\SchemaException","type":"::"}
23.05.2024 09:43:46 | Restoring database
23.05.2024 09:50:03 | Done!

**Comment by rratsun** [comment]
You did not update the system for a long period :(

In 1.10.22 I have just fixed the migration 1.8.10. You can try again. 

**I strongly recommend you to save the copy of the system (files and DB dump) before update.** Too many versions, too many migrations. Even we did not tested such case.

**Comment by paultvis** [comment]
Hi, 

We had the system on auto update but that failed some time back and we did not notice, hence the old version. There seemed to have been a change in installation requirements some time back which led to the failure. I have just tried again and it has the same error.

Is there a way to stage the updates? Upgrade to something mid way?

Regards,

Paul

**Comment by rratsun** [comment]
The latest version of core now is 1.10.23 (but it is only the core. there are also pim module and others).
If you want to update the system by steps, you can set prefered version in module manager and then run update.

for example you can set: **~1.7.0** into the core and then run update. The system will update you project to the latest patch for 1.7.*

then you can do the same but set **~1.8.0** .... and so on and so on.

This way you can update the system step by step.

P.S.
~1.7.0 it is the same as >=1.7.0 <1.8.0   [1.7.0,1.7.1,1.7.2 ..... 1.7.99999]

^1.7.0 it is the same as >=1.7.0  [1.7.0,1.7.1 .... 1.8.2, 1.8.3 ....]

**Comment by paultvis** [comment]
Hi,

Got a lot further this time. Still seems to be something around addresses failing

23.05.2024 12:29:16 | Loading composer repositories with package information
23.05.2024 12:29:18 | Creating restore point
23.05.2024 12:29:32 | Updating dependencies
23.05.2024 12:30:05 | Package operations: 3 installs, 21 updates, 1 removal
  - Removing symfony/workflow (v5.4.28)
  - Updating atrocore/compatibilities (1.0.2 => 1.0.6): 
  - Updating symfony/polyfill-php80 (v1.28.0 => v1.29.0): 
  - Updating symfony/deprecation-contracts (v2.5.2 => v2.5.3): 
  - Updating symfony/polyfill-mbstring (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-intl-normalizer (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-ctype (v1.28.0 => v1.29.0): 
  - Updating symfony/event-dispatcher-contracts (v2.5.2 => v2.5.3): 
  - Updating symfony/event-dispatcher (v5.4.26 => v5.4.39): 
  - Updating paragonie/constant_time_encoding (v2.6.3 => v2.7.0): 
  - Updating phpseclib/phpseclib (3.0.23 => 3.0.37): 
  - Updating symfony/polyfill-php72 (v1.28.0 => v1.29.0): 
  - Updating symfony/polyfill-intl-idn (v1.28.0 => v1.29.0): 
  - Updating ezyang/htmlpurifier (v4.16.0 => v4.17.0): 
  - Updating caxy/php-htmldiff (v0.1.14 => v0.1.15): 
  - Installing ralouphie/getallheaders (3.0.3): 
  - Updating psr/http-factory (1.0.2 => 1.1.0): 
  - Installing guzzlehttp/psr7 (2.6.2): 
  - Updating atrocore/core (1.6.46 => 1.10.23): 
  - Updating atrocore/dam (1.5.22 => 1.8.3): 
  - Updating atrocore/pim (1.9.51 => 1.13.12): 
  - Updating twig/twig (v3.7.1 => v3.10.3): 
  - Installing jdorn/sql-formatter (v1.2.16): 
  - Updating atrocore/export-feeds (1.7.26 => 1.8.9): 
  - Updating atrocore/import-feeds (1.5.27 => 1.6.8): 
23.05.2024 12:30:25 | Writing lock file
23.05.2024 12:30:25 | Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> \Atro\Composer\PostUpdate::postUpdate
23.05.2024 12:30:25 | Updating list of used modules
23.05.2024 12:30:25 | Copying post-install & post-delete scripts for modules
23.05.2024 12:30:25 | Copying migration scripts
23.05.2024 12:30:25 | Clearing cache
23.05.2024 12:30:26 | Copying frontend files
23.05.2024 12:30:27 | Run migration Atro 1.6.51
23.05.2024 12:30:30 | Run migration Atro 1.6.54
object(PDOException)#755370 (8) {
  ["message":protected]=>
  string(80) "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'minimum_age'"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  string(5) "42S21"
  ["file":protected]=>
  string(73) "/var/www/atropim/vendor/atrocore/core/app/Atro/Migrations/V1Dot6Dot54.php"
  ["line":protected]=>
  int(35)
  ["trace":"Exception":private]=>
  array(17) {
    [0]=>
    array(5) {
      ["file"]=>
      string(73) "/var/www/atropim/vendor/atrocore/core/app/Atro/Migrations/V1Dot6Dot54.php"
      ["line"]=>
      int(35)
      ["function"]=>
      string(4) "exec"
      ["class"]=>
      string(3) "PDO"
      ["type"]=>
      string(2) "->"
    }
    [1]=>
    array(5) {
      ["file"]=>
      string(73) "/var/www/atropim/vendor/atrocore/core/app/Atro/Migrations/V1Dot6Dot54.php"
      ["line"]=>
      int(20)
      ["function"]=>
      string(4) "exec"
      ["class"]=>
      string(27) "Atro\Migrations\V1Dot6Dot54"
      ["type"]=>
      string(2) "->"
    }
    [2]=>
    array(5) {
      ["file"]=>
      string(70) "/var/www/atropim/vendor/atrocore/core/app/Atro/Composer/PostUpdate.php"
      ["line"]=>
      int(612)
      ["function"]=>
      string(2) "up"
      ["class"]=>
      string(27) "Atro\Migrations\V1Dot6Dot54"
      ["type"]=>
      string(2) "->"
    }
    [3]=>
    array(5) {
      ["file"]=>
      string(70) "/var/www/atropim/vendor/atrocore/core/app/Atro/Composer/PostUpdate.php"
      ["line"]=>
      int(89)
      ["function"]=>
      string(13) "runMigrations"
      ["class"]=>
      string(24) "Atro\Composer\PostUpdate"
      ["type"]=>
      string(2) "::"
    }
    [4]=>
    array(5) {
      ["file"]=>
      string(86) "phar:///var/www/atropim/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php"
      ["line"]=>
      int(236)
      ["function"]=>
      string(10) "postUpdate"
      ["class"]=>
      string(24) "Atro\Composer\PostUpdate"
      ["type"]=>
      string(2) "::"
    }
    [5]=>
    array(5) {
      ["file"]=>
      string(86) "phar:///var/www/atropim/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php"
      ["line"]=>
      int(142)
      ["function"]=>
      string(21) "executeEventPhpScript"
      ["class"]=>
      string(40) "Composer\EventDispatcher\EventDispatcher"
      ["type"]=>
      string(2) "->"
    }
    [6]=>
    array(5) {
      ["file"]=>
      string(86) "phar:///var/www/atropim/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php"
      ["line"]=>
      int(54)
      ["function"]=>
      string(10) "doDispatch"
      ["class"]=>
      string(40) "Composer\EventDispatcher\EventDispatcher"
      ["type"]=>
      string(2) "->"
    }
    [7]=>
    array(5) {
      ["file"]=>
      string(64) "phar:///var/www/atropim/composer.phar/src/Composer/Installer.php"
      ["line"]=>
      int(267)
      ["function"]=>
      string(14) "dispatchScript"
      ["class"]=>
      string(40) "Composer\EventDispatcher\EventDispatcher"
      ["type"]=>
      string(2) "->"
    }
    [8]=>
    array(5) {
      ["file"]=>
      string(76) "phar:///var/www/atropim/composer.phar/src/Composer/Command/UpdateCommand.php"
      ["line"]=>
      int(163)
      ["function"]=>
      string(3) "run"
      ["class"]=>
      string(18) "Composer\Installer"
      ["type"]=>
      string(2) "->"
    }
    [9]=>
    array(5) {
      ["file"]=>
      string(80) "phar:///var/www/atropim/composer.phar/vendor/symfony/console/Command/Command.php"
      ["line"]=>
      int(245)
      ["function"]=>
      string(7) "execute"
      ["class"]=>
      string(30) "Composer\Command\UpdateCommand"
      ["type"]=>
      string(2) "->"
    }
    [10]=>
    array(5) {
      ["file"]=>
      string(76) "phar:///var/www/atropim/composer.phar/vendor/symfony/console/Application.php"
      ["line"]=>
      int(835)
      ["function"]=>
      string(3) "run"
      ["class"]=>
      string(41) "Symfony\Component\Console\Command\Command"
      ["type"]=>
      string(2) "->"
    }
    [11]=>
    array(5) {
      ["file"]=>
      string(76) "phar:///var/www/atropim/composer.phar/vendor/symfony/console/Application.php"
      ["line"]=>
      int(185)
      ["function"]=>
      string(12) "doRunCommand"
      ["class"]=>
      string(37) "Symfony\Component\Console\Application"
      ["type"]=>
      string(2) "->"
    }
    [12]=>
    array(5) {
      ["file"]=>
      string(74) "phar:///var/www/atropim/composer.phar/src/Composer/Console/Application.php"
      ["line"]=>
      int(281)
      ["function"]=>
      string(5) "doRun"
      ["class"]=>
      string(37) "Symfony\Component\Console\Application"
      ["type"]=>
      string(2) "->"
    }
    [13]=>
    array(5) {
      ["file"]=>
      string(76) "phar:///var/www/atropim/composer.phar/vendor/symfony/console/Application.php"
      ["line"]=>
      int(117)
      ["function"]=>
      string(5) "doRun"
      ["class"]=>
      string(28) "Composer\Console\Application"
      ["type"]=>
      string(2) "->"
    }
    [14]=>
    array(5) {
      ["file"]=>
      string(74) "phar:///var/www/atropim/composer.phar/src/Composer/Console/Application.php"
      ["line"]=>
      int(113)
      ["function"]=>
      string(3) "run"
      ["class"]=>
      string(37) "Symfony\Component\Console\Application"
      ["type"]=>
      string(2) "->"
    }
    [15]=>
    array(5) {
      ["file"]=>
      string(50) "phar:///var/www/atropim/composer.phar/bin/composer"
      ["line"]=>
      int(66)
      ["function"]=>
      string(3) "run"
      ["class"]=>
      string(28) "Composer\Console\Application"
      ["type"]=>
      string(2) "->"
    }
    [16]=>
    array(4) {
      ["file"]=>
      string(30) "/var/www/atropim/composer.phar"
      ["line"]=>
      int(14)
      ["args"]=>
      array(1) {
        [0]=>
        string(50) "phar:///var/www/atropim/composer.phar/bin/composer"
      }
      ["function"]=>
      string(7) "require"
    }
  }
  ["previous":"Exception":private]=>
  NULL
  ["errorInfo"]=>
  array(3) {
    [0]=>
    string(5) "42S21"
    [1]=>
    int(1060)
    [2]=>
    string(35) "Duplicate column name 'minimum_age'"
  }
}
23.05.2024 12:30:30 | Run migration Atro 1.7.34
23.05.2024 12:30:30 | Run migration Atro 1.7.35
23.05.2024 12:30:36 | Run migration Atro 1.7.36
23.05.2024 12:30:36 | Run migration Atro 1.7.37
23.05.2024 12:30:36 | Run migration Atro 1.8.2
23.05.2024 12:30:36 | Run migration Atro 1.8.3
23.05.2024 12:30:36 | Run migration Atro 1.8.6
23.05.2024 12:33:42 | Run migration Atro 1.8.7
23.05.2024 12:33:43 | Run migration Atro 1.8.8
23.05.2024 12:33:43 | Run migration Atro 1.8.10
23.05.2024 12:33:44 | Run migration Atro 1.8.12
23.05.2024 12:33:46 | Run migration Atro 1.6.55
23.05.2024 12:33:46 | Run migration Atro 1.8.14
23.05.2024 12:33:48 | Run migration Atro 1.8.15
23.05.2024 12:33:50 | Run migration Atro 1.8.26
23.05.2024 12:33:50 | Run migration Atro 1.8.28
23.05.2024 12:33:52 | Run migration Atro 1.8.29
23.05.2024 12:35:23 | Run migration Atro 1.8.32
23.05.2024 12:35:25 | Run migration Atro 1.8.33
23.05.2024 12:35:25 | Run migration Atro 1.8.36
23.05.2024 12:35:27 | Run migration Atro 1.8.38
23.05.2024 12:35:31 | Run migration Atro 1.6.56
23.05.2024 12:35:34 | Run migration Atro 1.8.39
23.05.2024 12:35:36 | Run migration Atro 1.9.0
23.05.2024 12:35:36 | Run migration Atro 1.9.1
23.05.2024 12:39:24 | Run migration Atro 1.9.3
23.05.2024 12:39:24 | Run migration Atro 1.9.9
23.05.2024 12:39:25 | Run migration Atro 1.7.0
23.05.2024 12:39:59 | Run migration Atro 1.7.5
23.05.2024 12:39:59 | Run migration Atro 1.7.14
23.05.2024 12:39:59 | Run migration Atro 1.7.22
23.05.2024 12:39:59 | Run migration Atro 1.7.28
23.05.2024 12:39:59 | Run migration Atro 1.7.31
23.05.2024 12:39:59 | Run migration Import 1.5.30
23.05.2024 12:40:35 | Run migration Import 1.5.31
23.05.2024 12:40:36 | Run migration Import 1.5.42
23.05.2024 12:40:36 | Run migration Import 1.5.60
23.05.2024 12:40:38 | Run migration Import 1.5.62
23.05.2024 12:40:38 | Run migration Import 1.5.63
23.05.2024 12:40:39 | Run migration Import 1.5.69
23.05.2024 12:40:41 | Run migration Pim 1.10.1
23.05.2024 12:41:47 | Run migration Pim 1.11.25
23.05.2024 12:41:49 | Run migration Pim 1.10.2
23.05.2024 12:43:51 | Run migration Pim 1.11.26
23.05.2024 12:46:29 | Run migration Pim 1.10.3
23.05.2024 12:46:31 | Run migration Pim 1.10.6
23.05.2024 12:46:32 | Run migration Pim 1.10.7
23.05.2024 12:46:34 | Run migration Pim 1.10.8
23.05.2024 12:47:07 | Run migration Pim 1.10.19
23.05.2024 12:47:09 | Run migration Pim 1.10.20
23.05.2024 12:47:11 | Run migration Pim 1.11.3
23.05.2024 13:32:49 | Run migration Pim 1.11.20
23.05.2024 13:32:49 | Run migration Export 1.7.31
23.05.2024 13:32:50 | Run migration Export 1.7.34
23.05.2024 13:32:53 | Run migration Export 1.7.42
23.05.2024 13:32:53 | Run migration Export 1.7.62
23.05.2024 13:32:53 | Run migration Export 1.7.64
23.05.2024 13:32:55 | Run migration Export 1.7.65
23.05.2024 13:32:56 | Run migration Export 1.7.66
23.05.2024 13:32:56 | Run migration Export 1.7.68
23.05.2024 13:32:58 | Run migration Export 1.8.6
23.05.2024 13:33:00 | Run migration Atro 1.9.12
23.05.2024 13:33:04 | Failed! An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'street' in 'where clause' {"file":"\/var\/www\/atropim\/vendor\/doctrine\/dbal\/src\/Connection.php","line":1768,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"}
23.05.2024 13:33:04 | Restoring database
23.05.2024 13:46:44 | Done!

**Comment by paultvis** [comment]
Also ended up with some strange colours not seen before in the module manager

![image](https://github.com/atrocore/atrocore/assets/31490804/783ec1e6-6b30-4c0e-ab7c-f33d164945d9)

**Comment by rratsun** [comment]
In the newest version of core we have removed DAM, thats why you see red color. But it is too soon for you. Press cancel in module manager.

I have discovered our old migrations, please, do upgrade in several steps.

Step 1: Set version of core 1.7.0 then update.
Step 2: After success update go to administration and press Rebuild. Wait success.
Step 3: Go to module manager and set 1.7.14 for core and update again 
Step 4: After success update go to administration and press Rebuild. Wait success.
Step 5: Go to Module manager and set ^1.7.14 for core and update

This should help. Please tell if it helps.

**Comment by rratsun** [comment]
We are so sorry for that problems. Unfortunatelly, we can't change the past. Old migrations had been written with expectations that custumer makes updates regullary. We had already changed such behavior but old migrations had been kept.

**Comment by paultvis** [comment]
Not your fault! We have been so busy in other areas of the business I never even noticed that the updates had stopped. Atro drove a lot of growth, but that created issues in other areas of the business. Anyway,

I just set core to 1.7.0 but it will not run as the dependencies for Pim cannot be met. What would the matching PIM version be?

**Comment by paultvis** [comment]
Thanks for that. So, managed to progress a little but it failed at 1.8.32. I now cannot access the system. Are there any API calls to rebuild db etc that I could try before restoring?

**Comment by rratsun** [comment]
Did you do update according to my steps? Please write what you have done. Which steps were finished.

**Comment by paultvis** [comment]
Yes I did. Once past 1.7.14 I decided to move things on more slowly. I went to 1.8.0, that was fine. Went up move to 1.8.41 and it failed at 1.8.32

**Comment by paultvis** [comment]
I should say after the roll back in the 1.8.0 - 1.8.41 upgrade the system was not left usable. 

I am going to repeat the process up to 1.8.30 or something like that then take a backup so that becomes the restore point

**Comment by atrolex** [comment]
Hello @paultvis i see, you problems are not trivial, and it seems to be impossible to solve your problems via communication here. We need to look inside of your system and it will take some additional time for sure. We can offer this as paid support, if you are interested, contact us via our contact form on the website. Alternatively you restore your system from the backup, to make it work, export all the data, install the new system and import all the data there.
