### ISSUE TITLE
Issues Running File Import using Remote File Import Module

### ISSUE THREAD

**Issue by paultvis** [atrocore/atrocore#1289]
We are having issues running imports using the remote file import module. We have created a new import, giving a path for each file to import. Giving 'file:///var....' in the url results in error

Download for 'file:///var/www/atropim/upload/upl_web/prod_images/ffcvh0pkr0y.jpg' failed

**Comment by paultvis** [comment]
As per my email, I get the error 
[2024-06-20T10:17:12.663035+00:00] Log.WARNING: E_WARNING: preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 0 {"code":2,"message":"preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 0","file":"/var/www/atropim/vendor/atrocore/import-remote-file/app/Services/ImportFeed.php","line":46} []

if I attach a file and run the import. If I upload and import, using the same file that has been attached to the import it runs, but we get the download failed error.

**Comment by paultvis** [comment]
Is there any update to this? I see the import module upgraded over the weekend but it appears it is still not working

**Comment by AnnZast** [comment]
Hello Paul,
we have created a task in our internal system and are currently working on your issue.
We'll let you know when it's fixed.

**Comment by paultvis** [comment]
Thanks for the update. We are keen to get this resolved as this is blocking us from adding new products and we are now renting the module but are unable to use it.

**Comment by paultvis** [comment]
Following the update to PIM, this is still not working. Same issues, if the import file is uploaded and stored in the import configuration, the job does not start.

If we import the file using Upload and Import, the task starts but all imports fail as it cannot copy the file. Can we still use the 'file' url type?

**Comment by rdzouk** [comment]
Hello Paul,
You can use the "File" url type on Core 1.10.35.
For imports of type "path", only files that are present in  the folder specified in "Dir Path" will be imported
I already updated you environment, you can can check imports again

**Comment by paultvis** [comment]
Thanks. I will try this now. So in the configuration we need to specify the path. We have been setting the file mask to * - is that correct? And then only files listed in our CSV will be imported?

 

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

**Comment by rdzouk** [comment]
You can set  ".*" to import every file in the directory
To import only csv file you can set ".*\.csv"

**Comment by paultvis** [comment]
I can see that you successfully imported on our system a couple of days ago. I have created a smaller file, exactly the same format as the one you imported but it is still failing. Still giving invalid url.

 

I am getting very confused by this

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

**Comment by paultvis** [comment]
Hi again,

 

Can you me what was done between the two imports on 02/07. They seem to use the same file, the first one failed and the second worked

 



 

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

 

From: Paul Tucker ***@***.***> 
Sent: 04 July 2024 11:02
To: 'atrocore/atrocore' ***@***.***>; 'atrocore/atrocore' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [atrocore/atrocore] Issues Running File Import using Remote File Import Module (Issue #1289)

 

I can see that you successfully imported on our system a couple of days ago. I have created a smaller file, exactly the same format as the one you imported but it is still failing. Still giving invalid url.

 

I am getting very confused by this

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

**Comment by paultvis** [comment]
Hi,

 

I resolved the issue here. I see that you had updated the column headings in the configuration. I am going to raise a defect/issue as the error handling in the import module is very weak. We have been running files that do not match the configuration but the import “runs”, reports success but imports nothing. 

 

Regards,

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

 

From: Paul Tucker ***@***.***> 
Sent: 04 July 2024 17:57
To: 'atrocore/atrocore' ***@***.***>; 'atrocore/atrocore' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [atrocore/atrocore] Issues Running File Import using Remote File Import Module (Issue #1289)

 

Hi again,

 

Can you me what was done between the two imports on 02/07. They seem to use the same file, the first one failed and the second worked

 



 

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

 

From: Paul Tucker ***@***.*** ***@***.***> > 
Sent: 04 July 2024 11:02
To: 'atrocore/atrocore' ***@***.*** ***@***.***> >; 'atrocore/atrocore' ***@***.*** ***@***.***> >
Cc: 'Author' ***@***.*** ***@***.***> >
Subject: RE: [atrocore/atrocore] Issues Running File Import using Remote File Import Module (Issue #1289)

 

I can see that you successfully imported on our system a couple of days ago. I have created a smaller file, exactly the same format as the one you imported but it is still failing. Still giving invalid url.

 

I am getting very confused by this

 

Paul

 

Paul Tucker

Vision Marine

Tel: 01383 807 444

**Comment by paultvis** [comment]
This issue is being closed. Imports are now working, however still issues but for a new defect
