### ISSUE TITLE
After upgrade to version 1.10.34 import fail to import specific option from list

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#1291]
I get error in import log (translated from my language):
Value 'z654d173fa42f7635' for field 'In collection' is not valid.
This error was not there before the update.
"In collection" is in this case a field added to entity products, as a list type with a simple Yes / No selection, and been there a long time now.
The Yes is updated, but the No don´t.

I have also attribute of the same type, and this also fails with same result.

I wonder if the fix stated in Release Note 1.10.34: "Improved import speed for list options" have made this ?

**Comment by rratsun** [comment]
Error means that import try to add option to the field (or attribute) and that option does not exist in List (that you choose for field or attribute). I recommend to use field Code when you importing options, because code is unique for all options, but name is not. That is why system found duplicate and tried to add wrong option to the field.

**Comment by exeqtwasnotfree** [comment]
ahaa, okey. But I don´t think I can use code for this application.
We have 3 different lists, with different variations of Yes/No.
![bild](https://github.com/atrocore/atrocore/assets/99046110/ded742cc-2a04-4449-abed-71dfe0cdb6a2)
I think I have to use the Value.

**Comment by exeqtwasnotfree** [comment]
Sorry to come back to this, but after updating 2 days ago, the export, exporting the ID of several options, instead of the Value as it have been and is sett to do.
I'm investigating now, and it seems intermitted, export of just a cupule of products can sometime work, and sometime not.
