### ISSUE TITLE
Export sometimes return option ID instead of value

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#1293]
I can´t find what is the issue.
I have several exports, that since updating 2024-07-02 to versions:
  - Upgrading atrocore/atrocore-legacy (1.0.7 => 1.0.8)
  - Upgrading atrocore/core (1.10.34 => 1.10.35)
  - Upgrading atrocore/export-feeds (1.8.14 => 1.8.15)
  - Upgrading atrocore/import-feeds (1.6.17 => 1.6.18)
  - Upgrading atrocore/pim (1.13.16 => 1.13.17)
 
Some of the lists, exporting the ID instead of value.
If I manual run the export on a specific product the export works.
If I experiment with selecting 5-25 products a bit random and export, i sometime get the value, and sometime gets the ID, and I can´t figure out the cause.
Both single-option and multi-option have the problem.
Not all "columns" in an export have the problem at the same time, but some of the fields are more prone to fail than others.

And I cant see the code for export, on github anymore, so I don´t know what's changed in export-feeds (1.8.14 => 1.8.15)

**Comment by rzablodskyi** [comment]
Hello, @exeqtwasnotfree. We have already fixed this issue. For correctly work you need these modules version - Export 1.8.15 and Core 1.10.39. Stable Core 1.10.39 version will release soon.

**Comment by exeqtwasnotfree** [comment]
Finally I manage to upgrade to 1.10.40 and this problem is no more.
