### ISSUE TITLE
Displaying same images (files) of product in different channels

### ISSUE THREAD

**Issue by Stelejent** [atrocore/atrocore#1300]
Hello.
When selecting one image (file) for a product in different channels, there is no possibility of editing them later - they are hidden and not displayed.

Example:
1. https://demo.atropim.com/#Product/view/21321
2. files tab
3. 'Select' some file and set channel 'Retailer' (for example)
4. 'Select' the same file 
5. At this point we should have the same image in two different channels. But in product images, only one is displayed, and the other is hidden and clicking on the "Show more" button does not show it..

**Comment by AnnZast** [comment]
Hello,

You are right, both files should be displayed on the product page. We will fix this in the next release

**Comment by Stelejent** [comment]
Issue resolved. 
Thank you.
