### ISSUE TITLE
Add `RewriteBase /` to htaccess

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#146]
To run AtroPIM I need to change the .htaccess after every update and add back `RewriteBase /` else it wouldn't run.

It should not affect other environments, since it seems to be a [standard setting for Wordpress](https://wordpress.org/support/article/htaccess/) that's supposed to run everywhere.

```htaccess
RewriteEngine On
RewriteBase /
```

**Comment by marcus-at-localhost** [comment]
That wasn't the case anymore with the latest updates. Is htaccess excluded from future updates? Or only gets overwritten if something changes in there? How does that work? If I can safely keep my changes, then this can be closed, unless you see it as a change to expand compatibility.

**Comment by rratsun** [comment]
htaccess updating only if it needs via migration. I've added 'RewriteBase /' to htaccess file, so in the futures releases everything will be OK.
