### ISSUE TITLE
Following through the install instructions on Ubuntu 18.04

### ISSUE THREAD

**Issue by baldgzr** [atrocore/atrocore#190]
Following through the install instructions on Ubuntu 18.04 

The following command:

> sudo git clone https://github.com/atrocore/skeleton-pim-no-demo.git . && php composer.phar self-update && php composer.phar update
> Cloning into '.'...
> remote: Enumerating objects: 32, done.
> remote: Counting objects: 100% (32/32), done.
> remote: Compressing objects: 100% (27/27), done.
> remote: Total 32 (delta 9), reused 12 (delta 3), pack-reused 0
> Unpacking objects: 100% (32/32), done.

Generates this error:

> Cannot create cache directory /home/user/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
> Cannot create cache directory /home/user/.composer/cache/files/, or directory is not writable. Proceeding without cache
> Failed! The new version of the composer can't be copied. Try to download manually 'https://packagist.atrocore.com/composer/composer.phar'.

I'm confused, any ideas or suggestions are much appreciated.

Thank you.

_Originally posted by @baldgzr in https://github.com/atrocore/atrocore/discussions/189_

**Comment by rratsun** [comment]
Discussed here https://github.com/atrocore/atrocore/discussions/189
