### ISSUE TITLE
Installation not possible because of the "Error: Not Found (404)"

### ISSUE THREAD

**Issue by Lunatic-999** [atrocore/atrocore#288]
I installed successfully all that was needed in your manual, but the installation wizard doesn't start. The /api/v1/Installer/getTranslations cannot be found and indeed, the whole directory /api/ doesn't exist at all. What may I have missed? Thanks.

![image](https://user-images.githubusercontent.com/99598337/153755414-bfa396f8-bc27-47a6-a8cb-6d151f53c3d8.png)

**Comment by 4lexo** [comment]
With 99% propability I would say your webserver is not properly configured. If you are using apache make sure mod_rewrite is enabled.
Execute: 
```
sudo a2enmod rewrite
sudo systemctl restart apache2
```

**Comment by Lunatic-999** [comment]
mod_rewrite was enabled already.

**Comment by Lunatic-999** [comment]
> With 99% propability I would say your webserver is not properly configured. If you are using apache make sure mod_rewrite is enabled. Execute:
> 
> ```
> sudo a2enmod rewrite
> sudo systemctl restart apache2
> ```

mod_rewrite was enabled already.

**Comment by 4lexo** [comment]
Than it is because of this:

![image](https://user-images.githubusercontent.com/33658481/153756861-a9894d03-e1eb-4bb7-939d-5eeb242a6832.png)

You need to have this option.

**Comment by gunjubas** [comment]
I have a same issue, but my root cause was PHP version (I using 8.3 and 8.2) but Atropim show me installer only on 8.1.30.
