### ISSUE TITLE
Getting error while rebuilding database. see log file for details.

### ISSUE THREAD

**Issue by rakibulinux** [atrocore/atrocore#29]
Hello, All, I am getting error while rebuilding database. see log file for details. Can you tell me how I can fix this error? Also can you please tell me how I can check the logs?

https://user-images.githubusercontent.com/59226530/103071523-f2eb3a80-45ed-11eb-9fcb-fef5832b1692.mov

![Screenshot 2020-12-24 at 1 42 19 PM](https://user-images.githubusercontent.com/59226530/103071552-00a0c000-45ee-11eb-8a0c-a826a6f6c1e3.png)

Regards

**Comment by rratsun** [comment]
Hello
All project logs you can find here /data/logs/*. 
I suppose that you did not do this step https://nimb.ws/i95ZIK, so project doesn't have permissions to create files and it can be related with getting error.

**Comment by rakibulinux** [comment]
Thanks for the fast reply. I was changed the owner before install but still the same problem. You can see my permission. Please check the logs.

[espo-2020-12-24.log](https://github.com/atrocore/atrocore/files/5739130/espo-2020-12-24.log)

![Screenshot 2020-12-24 at 3 45 41 PM](https://user-images.githubusercontent.com/59226530/103080209-90029f00-45ff-11eb-9b22-1f39f0e253d6.png)

**Comment by rratsun** [comment]
try to install latest versions of pim and dam modules. For this go to composer.json file and change 
"atrocore/pim": "~1.0.0" -> "atrocore/pim": "\*"
"atrocore/dam": "~1.0.0" -> "atrocore/dam": "\*"

after call "composer update"

and change user-group again https://nimbusweb.me/nimbus-screenshots/fc71d95d381e5e4fba4e784617b50c7c

It should help.

**Comment by rratsun** [comment]
And please remove custom/Espo/Custom/Resources/metadata/entityDefs/Product.json file before calling "composer update". There is small bug here.

**Comment by rakibulinux** [comment]
I am getting this error. After "composer update".
![Screenshot 2020-12-24 at 6 56 08 PM](https://user-images.githubusercontent.com/59226530/103089989-f694b680-4619-11eb-9bb3-4a9e3f806295.png)

**Comment by rratsun** [comment]
run "php index.php sql diff --run"

**Comment by rakibulinux** [comment]
Now getting this error: 
![Screenshot 2020-12-24 at 7 04 37 PM](https://user-images.githubusercontent.com/59226530/103090346-fe088f80-461a-11eb-8ead-4e6b182fd198.png)

Permission is okay.

![Screenshot 2020-12-24 at 7 05 47 PM](https://user-images.githubusercontent.com/59226530/103090409-27c1b680-461b-11eb-8761-20b8fa13b493.png)

**Comment by rratsun** [comment]
Very strange behavior. Please, go to composer.json again and remove "atrocore/dam" at all. Then run "composer update". Then prepare permissions. Then try to install project without dam module. In case of success installation go to module manager and install dam module.

**Comment by rakibulinux** [comment]
Install done without atrocore/dam | I should try it now, module manager and install dam module, right?
![Screenshot 2020-12-24 at 7 18 28 PM](https://user-images.githubusercontent.com/59226530/103090980-eb8f5580-461c-11eb-8f13-67b33eb7bd8c.png)

**Comment by rratsun** [comment]
Ok. If you need DAM module then install the module by ModuleManager.

**Comment by rakibulinux** [comment]
Now all is working, Thanks for the kind help.

**Comment by rakibulinux** [comment]
Hello, @rratsun, Sorry for disturbing you again. I am getting one error for the new installation. Can you please check it?
![Screenshot 2020-12-25 at 12 47 20 AM](https://user-images.githubusercontent.com/59226530/103103412-185a6180-464b-11eb-865b-37f15ae48f28.png)

**Comment by rratsun** [comment]
Hello, try to reinstall. Now it should works.

**Comment by rakibulinux** [comment]
Now it's working fine, Thanks for the kind help again.
