### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by alaamh** [atrocore/atrocore#292]
Thank you for the wonderful boilerplate, Amazing work.

I have followed the installation guide to install AtroPINE and AtroDAM with demo data, but unfortunately I can see the dump data is not matching the table structure in the database. for example:

```
INSERT INTO `user` (id,deleted,is_admin,user_name,password,salutation_name,first_name,last_name,is_active,is_portal_user,is_super_admin,title,gender,created_at,default_team_id,avatar_id,created_by_id,email_address,phone_number,portal_id,account_id) ....
```

```
**MySQL said**
#1054 - Unknown column 'email_address' in 'field list'
```

Appreciate, if you please share the latest updated demo data.

**Comment by atrolex** [comment]
I think during installation you can see from where demo data is downloaded.
