### ISSUE TITLE
Amount of "Success" Export/Import Jobs to be stored, is always +1

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#304]
Hello,
Both Import and Export have this problem.
Amount of Success Export/Import Jobs to be stored is always one more than the setting: "Amount of "Success" Export Jobs to be stored" 
If you set it to 1 you get 2 jobs, if it´s set to 10 you get 11.
You can´t set it to 0, so I can´t make it so that only one successful job is left.

Something I´m doing wrong or is there a little bug hiding somewhere?

**Comment by rratsun** [comment]
Fixed in last update.
