### ISSUE TITLE
Installation fails "require.atrocore/core : unbound version constraints (*) should be avoided"

### ISSUE THREAD

**Issue by widzewwadzaw** [atrocore/atrocore#320]
Hi 

Following the instructions: https://github.com/atrocore/docs/blob/master/atrocore/admin-guide/installation.md
Step 3.2 fails 

did another installation Tuesday last week with no issues.

Composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.atrocore/core : unbound version constraints (*) should be avoided
require.atrocore/pim : unbound version constraints (*) should be avoided
require.atrocore/dam : unbound version constraints (*) should be avoided
require.atrocore/export-feeds : unbound version constraints (*) should be avoided
require.atrocore/import-feeds : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: [Composer\Downloader\TransportException] The "http://repo.packagist.org/packages.json" file could not be down                  loaded: failed to open stream: Connection timed out
Checking https connectivity to packagist: [Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be do                  wnloaded: failed to open stream: Connection timed out
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.10.1
PHP version: 7.4.3
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

**Comment by atrolex** [comment]
I think problem was server configuration issue.
