### ISSUE TITLE
Content Width in "New Products" View missing

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#347]
(Latest version)

Steps to reproduce:

1. Hide right panel in Products view (or any other Entries view)

![image](https://user-images.githubusercontent.com/1337223/172701449-4ddceaab-26a2-45bb-b251-045445508b9d.png)

2. Create New Product (Entry)
3. Main Content area width is not calculated.

![image](https://user-images.githubusercontent.com/1337223/172701847-2926ba15-2a6e-4de7-a92f-4b8bf1fa742c.png)

This affects all other views, not only Products!

**Comment by rratsun** [comment]
Fixed at 1.4.55
