### ISSUE TITLE
Templates and lightncandy version

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#40]
Hi,
I was setting up a template for products (I looked up the [EspoCRM example](https://www.espocrm.com/tips/pdf-template/)), unfortunately there is some discrepancy with the versions and there is no output.

This pulls in the latest lightncandy version of the 0.x branch (0.95)
https://github.com/atrocore/atrocore/blob/9c4cc4fd4e077755432957bfb06907d5ec2b7f5c/composer.json#L28

And here the file is referenced in all lower case (but it's `LightnCandy.php` in v0.95 `https://github.com/zordius/lightncandy/blob/v0.95/src/LightnCandy.php`)
https://github.com/atrocore/atrocore/blob/9c4cc4fd4e077755432957bfb06907d5ec2b7f5c/app/Espo/Core/Htmlizer/Htmlizer.php#L43

Should I just install 0.22 instead? But I don't want it to be overwritten with the AtroPIM updates :)

**Comment by rratsun** [comment]
We fixed described problem at 1.1.11

**Comment by rratsun** [comment]
In addition, you don't need to update version of "zordius/lightncandy". Pdf generation should work.
