### ISSUE TITLE
mysql server migration

### ISSUE THREAD

**Issue by Anil-Kumar-k** [atrocore/atrocore#508]
Hello,

I have configured atrcore and it is accessible. However mysql is on the same instance and I want to move it to an RDS server.
Is they any place where the steps are documented so that I can make the necessary changes.

Thanks in advance.

Regards
Anil

**Comment by rratsun** [comment]
1) You should create mysql dump from existing DB first
2) You should import your mysql dump into new mysql server
3) You should change DB configuration in ```/var/www/your_domain/data/config.php```
