### ISSUE TITLE
 Category import error

### ISSUE THREAD

**Issue by SJIngw** [atrocore/atrocore#529]
Hi,
 when i am trying to import categories  getting the following error. 
**An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction.**
what is the meaning of this error? and how should i overcome this issue?
Thank you

**Comment by atrolex** [comment]
This error means your have problems with your MySQL. You have something like a "deadlock" – maybe infinite loop somewhere. Why you have it, is hard to tell. MariaDB is currently not supported it you use it. Maybe your import feed configuration is wrong. Try to import something else, or, if you think this is an application error, provide more details: you file to be imported, screenshots of your configuration etc...

**Comment by SJIngw** [comment]
Hi, first of all thanks for your fast reply. Actually i imported
attributes, attribute groups, catalogs and even products also.only getting
this error by importing categories. Here is my configuration settings:
Import feed:
[image: image.png]
Export feed:
[image: image.png]
Error report:
[image: image.png]
one more thing, when i am configuring export feeds i have more fields which
are not presented for import feeds. for example catalogs and category tree.
Then how can i assign a category to catologs in import itself.

[image: image.png]     [image: image.png]

Thank you.

**Comment by SJIngw** [comment]
sorry by mistakenly i sent both import feeds. Here is the export feed.
[image: image.png]

**Comment by rratsun** [comment]
Please, re-send screenshots. For some reasons, screenshots are unavailable now. 
We want to try to reproduce the error in our installations, in case of bug - fix it.

**Comment by SJIngw** [comment]
Sure, here it is.
[image: image.png]
[image: image.png]

[image: image.png]

one more thing, when i am configuring export feeds i have more fields which
are not presented for import feeds. for example catalogs and category tree.
Then how can i assign a category to catologs in import itself.

[image: image.png]     [image: image.png]

**Comment by atrolex** [comment]
We see your screenshots like this:
![image](https://user-images.githubusercontent.com/33658481/204212605-3f504698-b45c-4685-a908-7344f25a9a6b.png)
Please re-upload.

**Comment by paultvis** [comment]
We had the same issue when trying to update categories. We resolved the issue by using category.id as the identifier. The error arrose when we tried to use another field as the identifier in the import. Does your import link to any other entities, and what field do you use to identify the entity?

The logic to identify secondary, linked entities seems to either block (as in this case) or at best not find a match when using imports.

**Comment by rratsun** [comment]
We will solve this bug in PIM 1.5.98. Please, wait.

**Comment by rratsun** [comment]
The problem solved. Please update your system to the latest version of PIM.
