### ISSUE TITLE
Your software is no longer open source... its restrictive.

### ISSUE THREAD

**Issue by multinerd** [atrocore/atrocore#589]
https://github.com/atrocore/atrocore/blob/master/README.md?plain=1#L5

A license either is an open-source license, or it restricts usage of the software to certain regions or types of usage. You cannot have both. (See criteria 1 & 5 here: https://opensource.org/osd)

That said, it is not your responsibility as the software creator to forbid people the usage when the law already forbids the usage. 
That serves no purpose (law overrides license, always) and would impose an unnecessary restriction when the law changes. 
It's the responsibility of the users of software to obey the law and not use unlawful tools.

I'll go one step further and say that from an [ethical standpoint](https://www.gnu.org/philosophy/free-software-even-more-important.html), it is very much your responsibility to make your software as free as possible, to help people keep (or regain) the control over their own computing. 

You're gonna have to decide whats more important, anti-russia virtue signaling, or remaining true to the nature of open source. Either way, you've been warned.

**Comment by atrolex** [comment]
You are right. We will remove this restriction. 
We just restrict support and paid offers for Russia.
