### ISSUE TITLE
exception thrown when generating a PDF with PDF Generator module

### ISSUE THREAD

**Issue by aharonach** [atrocore/atrocore#675]
Hello,
I'm getting an error when I try to generate a PDF using the built-in template (or any other template I tried to create).
In the error log I see this exception thrown:
`Uncaught Exception Error: "Call to a member function close() on null" at /public_html/vendor/atrocore/pdf-generator/app/Services/ChromeBrowser.php line 131 {"exception":"[object] (Error(code: 0): Call to a member function close() on null at /public_html/vendor/atrocore/pdf-generator/app/Services/ChromeBrowser.php:131)\n[previous exception] [object] (RuntimeException(code: 0): Chrome process stopped before startup completed. Additional info: sh: 1: exec: google-chrome: not found at /public_html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:410)"} []`

Any ideas?

**Comment by atrolex** [comment]
please do this:
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

**Comment by aharonach** [comment]
In which directory should I do it?
Also, if it's worth mention, my server is using an Intel processor with Ubuntu 20.04.

Thanks a lot!

**Comment by aharonach** [comment]
Thanks, I've installed chrome as you suggested, and I can also do `google-chrom --help` in the terminal with no problem,
but the PIM still throws the same mentioned error, unfortunately.

**Comment by atrolex** [comment]
Check also if you have proper configuration for the Site URL here: https://demo.atropim.com/#Admin/settings

**Comment by aharonach** [comment]
It's already been set up properly, unfortunately that's not the reason.

**Comment by atrolex** [comment]
please contact our support via email at support@, be ready to provide access data for us.
