### ISSUE TITLE
"Product Type" field is missing for "Product Bundles" module

### ISSUE THREAD

**Issue by aharonach** [atrocore/atrocore#676]
Hi,
I've installed the "Product Bundles" module. To create a bundled product, in the documentation it says that I should select the "Product Bundle" in the "Product Type" field, but no such field exists. It doesn't list in the fields of the "Product" entity, and also in the layout settings it's missing.

Thanks for your help!

**Comment by atrolex** [comment]
There is no such field anymore, it was deprecated. Any product can be a bundle.
