### ISSUE TITLE
Assigning an attribute group to a product family is failing by validation rule

### ISSUE THREAD

**Issue by aharonach** [atrocore/atrocore#679]
Hi,
When I try to add an attribute group to a product family I'm getting a validation error as follows:
`Error 400: Validation failed. 'productFamily_name' is required.`

I tried to set the "name" field for product family to non-required (just for testing) but I got another error:
`Error 400: Validation failed. 'attribute_name' is required.`

I tried to create new product family and new attribute group, rebuild the database, clear cache, perform `php index.php sql diff --run` and `php composer.phar restore`, but nothing helped.

**Comment by asapko** [comment]
Hello Aharon!
We created an internal issue for this. It will be fixed ASAP.

**Comment by asapko** [comment]
Hello Aharon!
The issue has been resolved and is on live the in the next update.
