### ISSUE TITLE
Can't upload company logo in "user interface" settings

### ISSUE THREAD

**Issue by aharonach** [atrocore/atrocore#684]
Hi,
As the title describes, I get an error when I try to upload a company logo, as follows:
`Error 400: No asset type provided.`

Thank you :)

**Comment by 0xCrawler** [comment]
Had the same with my profile avatar; I think you need to do the follow:

Create an asset type in Administration -> Asset Types (DAM section) and one need at least the "Assign automatically" checkbox active

My Example:
![image](https://user-images.githubusercontent.com/127828659/229698187-27e6f29e-7120-4f3a-849f-8b10dd8a0535.png)

After that, it should work

**Comment by aharonach** [comment]
It worked! 
Thanks :)
