### ISSUE TITLE
Mass Upload no working

### ISSUE THREAD

**Issue by giuseppe-ao** [atrocore/atrocore#790]
After the release of the new release, the system no longer allows for a bulk upload.

AtroDAM v1.5.12
AtroCore v1.6.6

![Schermata 2023-06-29 alle 15 36 34](https://github.com/atrocore/atrocore/assets/74664595/ed18ad40-0b87-44b1-b3cd-81281cb11066)

**Comment by rratsun** [comment]
Oh, yes. We will fix it ASAP.

**Comment by rratsun** [comment]
Should work at DAM 1.5.13
