### ISSUE TITLE
Can not update core to newest version

### ISSUE THREAD

**Issue by Grag-SimonWRIGHT** [atrocore/atrocore#819]
AtroСore: 1.5.80
Ubuntu 20.04.6 LTS

/var/www/my.pim-project# php composer.phar update 
or
/var/www/my.pim-project# php composer.phar self-update 
or
via Module-Page
nothing works for me. Any idea/
Thanks in advance.

10.08.2023 12:16:08 | Loading composer repositories with package information
10.08.2023 12:16:10 | Creating restore point
10.08.2023 12:16:38 | Updating dependencies
10.08.2023 12:16:46 | Nothing to install or update or delete
10.08.2023 12:16:46 | Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
10.08.2023 10:16:46 | Clearing cache
10.08.2023 10:16:47 | Done!

**Comment by Grag-SimonWRIGHT** [comment]
Hello,
{
    "name": "atrocore/skeleton-pim",
    "description": "Skeleton for AtroPIM",
    "homepage": "https://atropim.com",
    "minimum-stability": "stable",
    "require": {
        "atrocore/core": "*",
        "atrocore/pim": "*",
        "atrocore/dam": "*",
        "atrocore/export-feeds": "*",
        "atrocore/import-feeds": "*",
        "atrocore/revisions": "*",
        "atrocore/product-bundles": "*",
        "atrocore/pdf-generator": "*",
        "atrocore/import-feeds-http": "*",
        "atrocore/import-feeds-database": "*",
        "atrocore/export-feeds-http": "*",
        "atrocore/connector": "*",
        "atrocore/completeness": "*",
        "atrocore/advanced-classification": "*",
        "atrocore/tasks": "*",
        "atrocore/pm": "*",
        "atrocore/pricing": "*"
    }
}

**Comment by rratsun** [comment]
It looks like, that the license for the premium module(s) has been expired. Write to our support.
