### ISSUE TITLE
Can´t add or change Classification on Product

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#846]
Hello
When I try to add or change Classification on a product I get:

`Error 200: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction`

Trying to mass-update or if I try to change by import, if I have the Classification field connected, I get the same error.

If I try to create the product with import and have the Classification connected, I get
`Import\FieldConverters\LinkMultiple::getForeignEntityName(): Argument #1 ($config) must be of type array, string given, called in /var/www/pim2/vendor/atrocore/import-feeds/app/FieldConverters/LinkMultiple.php on line 40`

If I go to the Classification and add the product from there, it works fine.
If I select a Classification before i save when I create a new product, it works.
If I delete Classification from edit product, it works, but can´t add class again.

Same behaviour exists on 2 different sites.

I have tried install latest patches, reboot server, look in the database for any locks, (timeout is set to 50sec).

Anything else I can try to troubleshoot this?

**Comment by exeqtwasnotfree** [comment]
I have discovered I can´t import any attribute, not even a simple text-field works.
Something is terrible wrong, troubleshooting continues tomorrow.....

**Comment by rratsun** [comment]
Try to update the system

**Comment by rratsun** [comment]
What versions you have now?

**Comment by exeqtwasnotfree** [comment]
I´m running: core 1.6.45  pim 1.9.49  import 1.5.25
I have tried updating 2 times this week.

**Comment by rratsun** [comment]
The problem ```General error: 1205 Lock wait timeout exceeded; try restarting transaction``` has been fixed in PIM 1.9.51.
Problem with import has been fixed in Import 1.5.25.
