### ISSUE TITLE
Mass updates of required multi-language fields that are empty fail silently

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#859]
The “Name” field of most entities is usually set as multi-language and required.
When adding a new language for the entities, this new “Name” field is typically empty.
Trying to edit an entity in inline-mode usually throws an error (the toast msg on top of the app) saying something like “'Name / zh_CN' can't be empty” or so.
By using the Mass-Update from the listing, any update fails silently, but I get a success message. It's only obvious in the logs that something went wrong.

I noticed this by using the translation module to mass-translate empty fields, and was wondering why it didn't work (only if there was an entry set in the new language field).

Removing the “required” attribute temporarily allows me to mass-update.

**Comment by AnnZast** [comment]
Hello Marcus. Thank you for your request. This bug has already been fixed
