### ISSUE TITLE
How to add Custom TwigFunction?

### ISSUE THREAD

**Issue by Vladzimir** [atrocore/atrocore#958]
After canceling the formulas, the question arose as to how to add your own functions to Twig

**Comment by rratsun** [comment]
hello,

Example:
https://github.com/atrocore/atropim/blob/master/app/Resources/metadata/twig/functions.json

**Comment by Vladzimir** [comment]
But if you change this file, it will be overwritten during the update!
How can I add it without this happening?

**Comment by rratsun** [comment]
I just showed you an example. If you have your own module you need to do it there. If not, you can create such file in **custom** folder (custom/Espo/Custom/Resources/metadata/twig/functions.json)

**Comment by Vladzimir** [comment]
In 1.10.40 this not work?!

**Comment by rratsun** [comment]
Yes. We've removed the ability to write custom code in the custom dir. If you need to develop something, you will need to develop your custom module. You can read more about our decision at https://github.com/atrocore/atrocore/issues/1294.
